.github/workflows/05-codeql.yml: rename and remodel following NUT upstream example
Signed-off-by: Jim Klimov <jimklimov+nut@gmail.com>

diff --git a/.github/workflows/05-codeql.yml b/.github/workflows/05-codeql.yml
--- a/.github/workflows/05-codeql.yml
+++ b/.github/workflows/05-codeql.yml
@@ -1,7 +1,7 @@
 # The contents below are based on sample configuration from CodeQL
 # and on the variant of that file used in the main NUT repository.
 #
-name: "CodeQL"
+name: "GHA-05: CodeQL"
 
 on:
   push:
@@ -34,13 +34,16 @@ jobs:
           # Build with OS-provided NUT package (or build v2.8.0 if pkg is too old), or NUT trunk?
         os: [ 'ubuntu-latest' ]
           # TOTHINK: windows-latest, macos-latest?
-        build-mode: [ 'none' ]
+        build-mode: [ 'manual' ]
           # https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages
-          # Abusing "none" here to try building with ccache (and
+          # Abusing "manual" here to try building with ccache (and
           # have codeql not intercept that build but parse C/C++
           # files on its own), and "manual" to custom-build without;
           # the "autobuild" mode is handled by codeql itself but
           # would probably ignore our CC/CXX setting
+          # NOTE: We do not add ccache to PATH when actually compiling NUT code
+          # (we only speed up "configure" stages), so compilation always happens
+          # and is parsed by current CodeQL detectors of the day as they evolve!
         compiler: [ 'CC=gcc CXX=g++', 'CC=clang CXX=clang++' ]
 
     steps:
@@ -49,13 +52,13 @@ jobs:
 
     # Using hints from https://askubuntu.com/questions/272248/processing-triggers-for-man-db
     - if: matrix.language == 'cpp' && matrix.os == 'ubuntu-latest'
-      name: Initialize dependencies (Ubuntu)
+      name: NUT CI Prerequisite packages (Ubuntu)
       run: |
         echo "set man-db/auto-update false" | sudo debconf-communicate
         sudo dpkg-reconfigure man-db
-        sudo apt-get update
+        sudo apt update
         case x"${{matrix.compiler}}" in x*clang*) sudo apt install clang ;; x*) sudo apt install gcc g++ ;; esac
-        sudo apt-get install libxpm-dev libxext-dev libupsclient-dev libc6-dev-amd64-cross libgcc-s1-amd64-cross ccache
+        sudo apt install libxpm-dev libxext-dev libupsclient-dev libc6-dev-amd64-cross libgcc-s1-amd64-cross ccache
         date > .timestamp-init
 
     - name: Prepare ccache
@@ -122,9 +125,15 @@ jobs:
       uses: github/codeql-action/init@v3
       with:
         languages: ${{ matrix.language }}
-        queries: +security-and-quality
         build-mode: ${{ matrix.build-mode }}
+        # If you wish to specify custom queries, you can do so here or in a config file.
+        # By default, queries listed here will override any specified in a config file.
+        # Prefix the (whole) list here with "+" to use these queries and those in the config file.
+        # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
+        queries: +security-extended,security-and-quality
 
+    # Autobuild attempts to build any compiled languages  (C/C++, C#, Go, or Java).
+    # If this step fails, then you should remove it and run the build manually (see below)
     # https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages
     - if: matrix.build-mode == 'autobuild'
       name: Autobuild
@@ -134,21 +143,29 @@ jobs:
         CODEQL_EXTRACTOR_CPP_AUTOINSTALL_DEPENDENCIES: false
 
     - if: matrix.build-mode != 'autobuild' && matrix.language == 'cpp'
-      name: WMNut CI Build
+      name: WMNut CI Build Configuration
       run: |
         case x"${{matrix.build-mode}}" in
-        xnone)
+        xmanual)
             PATH="/usr/lib/ccache:$PATH" ; export PATH
             CCACHE_COMPRESS=true; export CCACHE_COMPRESS
             ccache --version || true
             ;;
-        xmanual|*)
-            echo "NOTE: NOT USING CCACHE for the CI-tested code base" >&2
+        xnone|*)
+            echo "NOTE: NOT USING CCACHE for the CI-tested code base configuration" >&2
             ;;
         esac
         ( ${{matrix.compiler}} ; echo "=== CC: $CC => `command -v $CC` =>" ; $CC --version ; echo "=== CXX: $CXX => `command -v $CXX` =>" ; $CXX --version ) || true
-        ./autogen.sh
+        ./autogen.sh && \
         ./configure ${{matrix.compiler}} --enable-debug --enable-Werror
+
+    # NOTE: We do not add ccache to PATH here, so compilation always happens
+    # and is parsed by current CodeQL detectors of the day as they evolve:
+    - if: matrix.build-mode != 'autobuild' && matrix.language == 'cpp'
+      name: WMNut CI Build Compilation
+      run: |
+        echo "NOTE: NOT USING CCACHE for the CI-tested code base compilation" >&2
+        ( ${{matrix.compiler}} ; echo "=== CC: $CC => `command -v $CC` =>" ; $CC --version ; echo "=== CXX: $CXX => `command -v $CXX` =>" ; $CXX --version ) || true
         make -s -j 8 || exit
 
     - if: matrix.build-mode != 'autobuild' && matrix.language == 'cpp'
