.github/workflows/codeql.yml: store .timestamp-init in current workdir and delete after use
The `hashFiles()` method may only look at files under `GITHUB_WORKSPACE`
per https://docs.github.com/en/actions/reference/workflows-and-actions/expressions#hashfiles

Signed-off-by: Jim Klimov <jimklimov+nut@gmail.com>

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -52,7 +52,7 @@ jobs:
         sudo apt-get update
         case x"${{matrix.compiler}}" in x*clang*) sudo apt install clang ;; x*) sudo apt install gcc g++ ;; esac
         sudo apt-get install libxpm-dev libxext-dev libupsclient-dev libc6-dev-amd64-cross libgcc-s1-amd64-cross ccache
-        date > ~/.timestamp-init
+        date > .timestamp-init
 
     - name: Prepare ccache
       # Based on https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching#example-using-the-cache-action example
@@ -65,14 +65,16 @@ jobs:
             ~/.ccache
             ~/.cache/ccache
             ~/.config/ccache/ccache.conf
-        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('~/.timestamp-init') }}
+        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('/.timestamp-init') }}
         restore-keys: |
           ${{ runner.os }}-build-${{ env.cache-name }}
           ${{ runner.os }}-build-
           ${{ runner.os }}-
 
     - name: CCache stats before build
-      run: ccache -sv || ccache -s || echo "FAILED to read ccache info, oh well"
+      run: |
+        ccache -sv || ccache -s || echo "FAILED to read ccache info, oh well"
+        rm -f .timestamp-init
 
     - if: matrix.language == 'c-cpp' && matrix.os == 'ubuntu-latest'
       name: Initialize dependencies (ensure NUT 2.8.0+)
